# Generated by Django 5.0.2 on 2026-07-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='favoriterecipe',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
